version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: carddb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - card-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - card-network

  card-service:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/carddb
      SPRING_REDIS_HOST: redis
    depends_on:
      - postgres
      - redis
    networks:
      - card-network

volumes:
  postgres_data:
  redis_data:

networks:
  card-network:
    driver: bridge